export const users = [
  {
    id: 1,
    name: "John Doe",
    title: "Software Engineer",
    location: "San Francisco, CA",
    avatar: "https://via.placeholder.com/150",
    followers: 1200,
    posts: 35,
    following: 180,
  },
  {
    id: 2,
    name: "Jane Smith",
    title: "Product Manager",
    location: "New York, NY",
    avatar: "https://via.placeholder.com/150",
    followers: 980,
    posts: 50,
    following: 250,
  },
  {
    id: 3,
    name: "Michael Brown",
    title: "UX Designer",
    location: "Austin, TX",
    avatar: "https://via.placeholder.com/150",
    followers: 670,
    posts: 28,
    following: 145,
  },
  {
    id: 4,
    name: "Emily Davis",
    title: "Data Scientist",
    location: "Boston, MA",
    avatar: "https://via.placeholder.com/150",
    followers: 1540,
    posts: 40,
    following: 320,
  },
  {
    id: 5,
    name: "David Johnson",
    title: "DevOps Engineer",
    location: "Los Angeles, CA",
    avatar: "https://via.placeholder.com/150",
    followers: 890,
    posts: 45,
    following: 210,
  },
];
